export const navigationRoutes = {
    HOME: '/',
    EVENTS: '/events',
    AUTH: '/auth',
    PROFILE: '/profile',
    ALUMNI: '/alumni',
    ACHIEVEMENTS: '/achievements',
    INTERVIEW_EXPERIENCES: '/interview_experiences',
    CREATE_INTERVIEW_EXPERIENCES: '/interview_experiences/create',
    GALLERY: '/gallery',
    TEAM: '/team',
    NOTIFICATIONS: '/notifications',
    PROJECTS: '/projects',
    EDIT_INTERVIEW: '/interview_experiences/edit',
};